### ISSUE TITLE
(#198-P3) BUG - As a supporter, fields are read-only.  Can't edit or add address if not provided when account created

### ISSUE THREAD

**Issue by vmcf** [VMCAuctions/VMCAuction#173]
(#198) related to bug #9 on the bug report sheet
Page: Account Page	
Function: Real-bid Experience
URL:  http://dv1.elizabid.com/5c37f10eebab55098d4ff05c/users/account/joe@smith.com

**Comment by mariatrojo** [comment]
Per our conversation, this has been handled in task 265, closing this task.
